services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kornamnsvalet_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
