"use client";
import { useState, useTransition } from "react";
import type { ApprovalOverview, ApprovalResult, NameElection } from "@/server/name-election/service";
import { closeApprovalRound, declareWinner, movePresentation, openApprovalRound, prepareFinalVote, revealNextSuggestion } from "./actions";
export function ApprovalControls({ initialState, overview, results }: { initialState: NameElection; overview?: ApprovalOverview; results?: ApprovalResult[] }) {
  const [state, setState] = useState(initialState); const [confirmation, setConfirmation] = useState(false); const [pending, startTransition] = useTransition();
  const [selected, setSelected] = useState<number[]>(() => results?.slice(0, 5).map(({ id }) => id) ?? []); const [allowance, setAllowance] = useState(state.voteTokenAllowance ?? 3); const [closeConfirm, setCloseConfirm] = useState(false);
  const frontier = state.revealFrontier ?? -1; const position = state.presentationPosition ?? -1;
  function run(action: () => Promise<NameElection>) { startTransition(async () => { try { setState(await action()); } catch (error) { alert(error instanceof Error ? error.message : "Kunde inte ändra Approval Round."); } }); }
  if (state.phase === "draft") return <section className="card"><h2>Approval Round</h2><p>Öppna rondens frusna roster och Suggestions. Detta kan inte ångras.</p>{confirmation ? <><p>Efter öppning kan roster, innehåll och ordning inte ändras.</p><button disabled={pending} onClick={() => { setConfirmation(false); run(openApprovalRound); }}>Bekräfta öppning</button><button disabled={pending} onClick={() => setConfirmation(false)}>Avbryt</button></> : <button onClick={() => setConfirmation(true)}>Öppna Approval Round</button>}</section>;
  if (state.phase === "approval-closed") return <><section className="card"><h2>Approval-resultat</h2><p>Resultaten är synliga endast för Administratören.</p><ol>{results?.map((result) => <li key={result.id}><strong>{result.suggestion}</strong> — Ja {result.yayCount}, Nej {result.nayCount}, obesvarade {result.unansweredCount}, Approval Score {(result.approvalScore * 100).toFixed(1)}%</li>)}</ol></section><section className="card"><h2>Förbered Final Vote</h2><p>Välj medvetet två till tio Finalists. Fem är förvalda.</p>{results?.map((result) => <label key={result.id} style={{ display: "block" }}><input type="checkbox" checked={selected.includes(result.id)} onChange={() => setSelected((ids) => ids.includes(result.id) ? ids.filter((id) => id !== result.id) : [...ids, result.id])} /> {result.suggestion} — {result.motivation}</label>)}<label>Vote Token allowance <input type="number" min="1" step="1" value={allowance} onChange={(event) => setAllowance(Number(event.target.value))} /></label><button disabled={pending || selected.length < 2 || selected.length > 10} onClick={() => startTransition(async () => { try { const next = await prepareFinalVote(selected, allowance); setState((old) => ({ ...old, phase: "final-prepared", finalistIds: next.finalistIds, voteTokenAllowance: next.voteTokenAllowance })); } catch (error) { alert(error instanceof Error ? error.message : "Kunde inte förbereda Final Vote."); } })}>Öppna inte ännu — frys förhandsvisningen</button><p>En ensam acceptabel Suggestion kan utses som Winner utan Final Vote.</p>{results?.map((result) => <button key={`winner-${result.id}`} disabled={pending} onClick={() => startTransition(async () => { try { const next = await declareWinner(result.id); setState((old) => ({ ...old, phase: "complete", winnerSuggestionId: next.winnerSuggestionId })); } catch (error) { alert(error instanceof Error ? error.message : "Kunde inte utse Winner."); } })}>Utse {result.suggestion} till Winner</button>)}</section></>;
  if (state.phase === "final-prepared" || state.phase === "complete") return <section className="card"><h2>{state.phase === "complete" ? "Winner frusen" : "Final Vote förberedd"}</h2><p>{state.winnerSuggestionId ? `Winner Suggestion: ${results?.find(({ id }) => id === state.winnerSuggestionId)?.suggestion ?? state.winnerSuggestionId}` : `Finalists: ${state.finalistIds?.length ?? 0} · Vote Token allowance: ${state.voteTokenAllowance}`}</p></section>;
  return <section className="card"><h2>Approval Round</h2><p>Reveal Frontier: {frontier + 1} · Presentation Position: {position + 1}</p>{overview ? <><p>Besvarade på Presentation Position: {overview.answeredCount} · Helt ikapp: {overview.fullyCaughtUpCount}</p><ul>{overview.participants.map((participant) => <li key={participant.participantId}>{participant.displayLabel}: {participant.invitationStatus}, {participant.completionState}{participant.lastActivityAt ? ` · ${participant.lastActivityAt.toLocaleString("sv-SE")}` : " · ingen aktivitet"}</li>)}</ul></> : null}<button disabled={pending || frontier >= 31} onClick={() => run(revealNextSuggestion)}>Nästa Suggestion</button><div><button disabled={pending || position <= 0} onClick={() => run(() => movePresentation(position - 1))}>Föregående presentation</button><button disabled={pending || position >= frontier} onClick={() => run(() => movePresentation(position + 1))}>Nästa presentation</button></div>{frontier >= 31 ? <>{closeConfirm ? <><p>Ofullständiga Participants: {overview?.participants.filter((participant) => participant.completionState !== "complete").map((participant) => participant.displayLabel).join(", ") || "inga"}. Detta kan inte ångras.</p><button disabled={pending} onClick={() => startTransition(async () => { try { const ids = overview?.participants.filter((participant) => participant.completionState !== "complete").map((participant) => participant.participantId) ?? []; const next = await closeApprovalRound(ids); setState(next); setCloseConfirm(false); } catch (error) { alert(error instanceof Error ? error.message : "Kunde inte stänga Approval Round."); } })}>Bekräfta stängning</button><button onClick={() => setCloseConfirm(false)}>Avbryt</button></> : <button disabled={pending} onClick={() => setCloseConfirm(true)}>Stäng Approval Round</button>}</> : null}<p>Presentation: <a href="/present" target="_blank">öppna delad skärm</a></p></section>;
}
